# Generated by Django 5.1.7 on 2025-03-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_monitor', '0002_eldlog_stop_trip_delete_driverinfo_stop_trip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='pickup_location',
        ),
        migrations.AddField(
            model_name='trip',
            name='current_location_latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='current_location_longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoff_location_latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoff_location_longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_location_latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_location_longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_cycle_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
